# -*- coding: utf-8 -*-
"""Expectation Decideripynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTsQ2tumsZLrT74waLYN7B8SErNCUOkI

# Project: Expectation Decider Model

##Objective:
To design an analytical framework that predicts whether a student will pass a competitive mathematics exam using probability patterns derived from a simulated cohort of 200 students.

###Dataset Attributes Analyzed:

* study_hours: Weekly study duration.
* attendance: Lecture attendance percentage.
* group_discussion: Active participation indicator (Yes/No).  
*   previous_test_score: Marks from the prior internal assessment out of 100.
*    final_exam_pass: The target variable indicating success or failure (Pass/Fail).
"""

# Import our important libarary that will help us to do our analysis.
import numpy as np                 # for the mathmatical calculationn and the data generation.
import pandas as pd                 # for the analysis
import matplotlib.pyplot as plt      # This library is use for the visulization.
import seaborn as sns                 # This was also a visulization library.

# Set  the seed for every time get random values.
np.random.seed(42)

# Generate the 200 student data with the help of numpy and then convert it into a pandas data fram with the help of pandas library.
study_hours = np.random.randint(1, 40, size=200)
attendence = np.clip(np.random.normal(70 + study_hours*0.5, 15, 200),10, 100).astype(int)
group_discussion =  np.random.choice(['Yes', 'No'], size =200)
previous_test_score =  np.clip(np.random.normal(50 + study_hours*0.8 + (attendence)*0.2, 10, 200), 20, 100).astype(int)
prob_pass = 1 / (1 + np.exp(-(-5 + 0.1*study_hours + 0.05*attendence + 0.5*(group_discussion=='Yes') + 0.03*previous_test_score)))
final_exam_pass = np.where(np.random.rand(200) < prob_pass, 'Pass', 'Fail')

# Convvert this into a clean table.
student_data = pd.DataFrame({
    'study_hours' : np.random.randint(1, 40, size=200),
    'attendence' : np.clip(np.random.normal(70 + study_hours*0.5, 15, 200),10, 100).astype(int),
    'group_discussion' : np.random.choice(['Yes', 'No'], size =200),
    'previous_test_score' : np.clip(np.random.normal(50 + study_hours*0.8 + (attendence)*0.2, 10, 200), 20, 100).astype(int),
    'final_exam_pass' : np.where(np.random.rand(200) < prob_pass, 'Pass', 'Fail')


})

student_data.to_csv('Dataset.csv' , index=False)

"""## Part:1 Foundational Probability Concepts"""

# Provide at least three examples of probability events derived directly from the dataset.
# The first Event is the simple event, That is select a random student how study 15 Plus hours in a week.
event_a_df = student_data[student_data['study_hours']>15]

total_students = len(student_data)

event_a_count = len(event_a_df)

prob_a = event_a_count / total_students

print(f"Sample Space (Total Students): {total_students}")
print(f"Outcomes in Event A: {event_a_count}")
print(f"Probability of Event A, P(A): {prob_a:.4f}")

# Event b is : A randomly selected student actively participated in group discussions.
# Count of the student that is actively participated in group discusion.
event_b_df = student_data[student_data['group_discussion'] == 'Yes']

event_b_count = len(event_b_df)

prob_b = event_b_count / total_students

print(f"Outcomes in Event B: {event_b_count}")
print(f"Probability of Event B, P(B): {prob_b:.4f}")

# Event C is: A randomly selected student failed the competitive exam.
event_c_df = student_data[student_data['final_exam_pass'] == 'Failed']

event_c_count = len(event_b_df)

prob_c = event_c_count / total_students

print(f"Ouctomes in Event C:{event_c_count}")
print(f"Probability of Event C, P(C) :{prob_c:.4f}")

"""### Part:2  Empirical and Theoretical Events

Identify one scenario demonstrating empirical probability and one scenario demonstrating theoretical probability using the dataset.
"""

# The Empirical probability:what is the observed probability that a randomly selected student passed the competitive mathematics exam?
n_students = len(student_data)

pass_student =  student_data[student_data['final_exam_pass'] == 'Pass']

count_pass_student = len(pass_student)

emp_prob = count_pass_student / n_students

print(f"The empirical probability that  a randomly selected student pass the competitve maths exam is:{emp_prob:.2f}")

# If the educational institute theoretically assumes that a student's decision to participate in group discussions is a perfectly random binary choice, what is the expected probability of participation?
outcomes = ['Yes', 'No']
favorable_outcomes = 1 # for the yes

theor_prob = favorable_outcomes /len(outcomes)

print("--- Theoretical Probability ---")
print(f"Assumption: Group discussion is a perfectly random binary choice.")
print(f"Theoretical P(Discussion) = {theor_prob:.2f}")

"""### Part 3: Random Variable & Probability Distribution"""

# Define a random variable representing the "Number of students passing the final exam" out of 3 randomly selected students.
# 1.Calculate the probability of student who pass in the exam.
total_students = len(student_data)
pass_students = student_data[student_data['final_exam_pass'] == 'Pass']
count_pass_student = len(pass_student)
p = count_pass_student / total_students

# 2.Define the parameter.
n = 3
x_values = [0, 1, 2, 3]
probabilities = []

# For solving the combination formula .
import math

# 3.Calculate the P(X=x).
for x in x_values:
    combinations = math.comb(n, x)
    prob_x = combinations * (p**x) * ((1 - p)**(n - x))
    probabilities.append(prob_x)

# Construct the probability table.
distribution_table = pd.DataFrame({
    'X (Number of Students Passing)': x_values,
    'P(X = x)': probabilities
})

# 5. Calculate Mean and Variance
mean_x = n * p
variance_x = n * p * (1 - p)

# Display Results
print("Probability Distribution Table:")
print("-" * 40)
print(distribution_table.to_markdown(index=False))
print("\nStatistical Moments:")
print("-" * 40)
print(f"Mean (E[X]): {mean_x:.4f}")
print(f"Variance (Var(X)): {variance_x:.4f}")

"""### Part 4: Venn Diagram in Probability"""

from pandas.io.formats.style_render import Subset
from matplotlib_venn import venn2
# Draw a Venn diagram illustrating students who study more than 10 hours per week.
# Define the set based on the condition.

# student who have studey hours greater that 10.
set_a_study = set(student_data[student_data['study_hours']>10].index)

# Student who have 80 or more that 80% attendance.
set_b_attendance = set(student_data[student_data['attendence']>80].index)

# Initilize the plot.
plt.figure(figsize=(8, 6))

# Generate the venn.
venn2(
    subsets = (set_a_study, set_b_attendance),
    set_labels=('Study > 10 hours\n(Set A)', 'Attendance > 80%\n(Set B)'),
    set_colors=('#87CEEB', '#98FB98') # Light blue and light green
)

# 4. Add formatting and title
plt.title("Venn Diagram: Study Hours vs. Attendance Overlap", fontsize=14, fontweight='bold')
plt.show()

# 5. Print the mathematical counts for verification
print(f"Total students in Set A (Study > 10 hrs): {len(set_a_study)}")
print(f"Total students in Set B (Attendance > 80%): {len(set_b_attendance)}")
print(f"Total students in Intersection (A ∩ B): {len(set_a_study.intersection(set_b_attendance))}")

"""### Task 5: Contingency Tables and Core Probabilities"""

# Create a contingency table cross-referencing participation in group discussions (Yes/No) against final exam outcomes (Pass/Fail).
Contengency_table = pd.crosstab(student_data['group_discussion'], student_data['final_exam_pass'],margins=True)
print(Contengency_table)

# Calculate the joint probability of a student who "Participates in group discussion AND Passes exam".
students= student_data[(student_data['group_discussion'] == 'Yes') & (student_data['final_exam_pass'] == 'Pass')]
count = len(students)

joint_probabaility = count / total_students
print(f"P(Passed AND Group Discussion) = {joint_probabaility}")

# Calculate the overall marginal probability of a student who "Passes exam".
prob_pass = Contengency_table.loc['All', 'Pass'] / Contengency_table.loc['All', 'All']

print("Marginal Probability of Passing:", prob_pass)

# Calculate the conditional probability of a student who "Passes exam given participation in group discussion".
# Conditional probability:
# P(Pass | Group Discussion = Yes)

pass_and_discussion = Contengency_table.loc['Yes', 'Pass']
total_discussion = Contengency_table.loc['Yes', 'All']

conditional_probability = pass_and_discussion / total_discussion

print("P(Pass | Group Discussion = Yes):", conditional_probability)
print("Percentage:", conditional_probability * 100, "%")


print(
    f"Among students who participated in group discussions, "
    f"{conditional_probability:.2%} passed the exam."
)

"""### Part 6: Understanding Relationships"""

# Identifying the Relationship Between the Events.
if np.isclose(conditional_probability, p):
    print("The events are independent.")
else:
    print("The events are dependent.")

# Test whether they are mutually exclusive.
print("""There are 93 students who both participated in group discussions and passed the exam.

Therefore, the two events can occur simultaneously.
So:
 P({Pass} AND {Discussion}) > 0
Hence:
The events are not mutually exclusive.""")

"""### Part 7: Bayes Theorem Application"""

# Use Bayes Theorem to find the probability that a student passed the exam given they had high attendance.
# Given probabilities
p_high_attendance_given_pass = 0.70
p_high_attendance_given_fail = 0.40
p_high_attendance = 0.60

# Calculate P(Pass)
# P(H) = P(H|Pass)P(Pass) + P(H|Fail)P(Fail)

p_pass = (
    p_high_attendance - p_high_attendance_given_fail
) / (
    p_high_attendance_given_pass - p_high_attendance_given_fail
)

# Calculate P(Fail)
p_fail = 1 - p_pass

# Apply Bayes' Theorem
p_pass_given_high_attendance = (
    p_high_attendance_given_pass * p_pass
) / p_high_attendance

print(f"P(Pass) = {p_pass:.4f}")
print(f"P(Fail) = {p_fail:.4f}")
print(f"P(Pass | High Attendance) = {p_pass_given_high_attendance:.4f}")
print(f"Percentage = {p_pass_given_high_attendance:.2%}")